### ISSUE TITLE
Password Authentication?

### ISSUE THREAD

**Issue by SoraBytes** [Guthix/OldScape#7]
Can you use password authentication? It appears that it only takes a username to login (based on the database only requiring a username)

**Comment by BartvHelvert** [comment]
It is not supported right now. If you want to add it you need to add it [here](https://github.com/guthix/OldScape/blob/master/server/src/main/kotlin/io/guthix/oldscape/server/world/World.kt#L166). You can sende a `StatusResponse.INVALID_CREDENTIALS` if the password check fails. It will probably be fixed when de login server gets added.
